spring:
  application:
    name: loan-app

  datasource:
    url: jdbc:postgresql://localhost:5432/loan_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true




# db username = postgres
# db password = admin
# db port = 5432
# db name = laon_db